/run/numberOfThreads 20
#/run/numberOfEventsPerThread 1

/userconfig/PrimPartType gamma
/userconfig/PrimPartEnergy 1 MeV

/run/initialize

#/vis/open OGL
#/vis/drawVolume
#/vis/viewer/set/style surface
#/vis/scene/add/trajectories smooth
#/vis/scene/endOfEventAction accumulate 10
#/vis/geometry/set/visibility World
#/vis/geometry/set/forceCloud World
/g4cmp/producePhonons 1
/g4cmp/produceCharges 0
/g4cmp/samplingEnergy 0.01 eV

#/tracking/verbose 5
#/g4cmp/verbose 2

#/process/inactivate phononScattering
#/process/inactivate phononDownconversion
/run/beamOn 1000
#/run/beamOn 1
